---
title: "dots-usage"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{dots-usage}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r, include = F}
library(devtools)
library(magrittr)

load_all()
```

## Introduction

Chartjs is initialized in javascript as

```
new Chart(id, options)
```
where options contains a list(s) of data and options.

In the use_dots branch, this list is created in R (without help) and passed directly
to the options parameter.

```{r}
dots_input_example()
```

## Examples

Default sizing .. `knitr.defaultWidth = '100%'` not working?

```{r}
dots_input_example() %>% 
  chartjs()
```

`out.width='100%'`

```{r, out.width='100%'}
x <-
  dots_input_example()

x$data$datasets[[2]] <-
    list(label = 'dataset 2',
         data = c(4,1,3,2))

x %>% 
  chartjs()
```

`out.width='100%', out.height='500px'`

```{r, out.width='100%', out.height='500px'}
x$type = 'line'

x %>% 
  chartjs()
```

