---
title: "Using a list of options as input"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Using a list of options as input}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(chartjs4r)
```

## Introduction

Chartjs is initialized in javascript as

```
new Chart(id, options)
```
where `options` contains a list of data and options.

We can create a list of data and options and pass it directly to chartjs.

```{r}
cjs_list_input_example()
```

## Examples

`knitr.defaultWidth = '100%'` not working?

```{r}
cjs_list_input_example() %>% 
  chartjs()
```

chunk option: `out.width='100%'`

```{r, out.width='100%'}
x <-
  cjs_list_input_example()

x$data$datasets[[2]] <-
  list(label = 'dataset 2',
       data = c(4,1,3,2))

x %>% 
  chartjs()
```

chunk option: `out.width='100%', out.height='200px'`

```{r, out.width='100%', out.height='200px'}
x$type = 'line'

x %>% 
  chartjs()
```

chunk option: `out.width='100%'`

```{r, out.width='100%'}
x <- cjs_list_input_example()


x$data$datasets[[1]] <-
  modify_list(x$data$datasets[[1]],
              list(borderColor = rgb(1, 0, 0),
                   backgroundColor = rgb(1, 0, 0, 0.5),
                   borderWidth = 2,
                   borderRadius = 100,
                   borderSkipped = FALSE))

x %>% 
  chartjs()
```

